[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "firebase-applet-config.json"

[functions]
  directory = "api"
